#!/usr/bin/env bash

VERSION="1.2.1"
RC_FILE=~/.gitpromptrc

RED="\033[0;31m"
GREEN="\033[0;32m"
YELLOW="\033[0;33m"
BLUE="\033[0;34m"
MAGENTA="\033[0;35m"
CYAN="\033[0;36m"
RESET="\033[0m"
WHITE=$RESET
BLACK=$RESET

CLI_EXIT_STATUS_COLOR=$RED
CLI_TIME_COLOR=$RESET
CLI_BRACKET_COLOR=$BLUE
CLI_AT_COLOR=$RESET
CLI_USERNAME_COLOR=$GREEN
CLI_HOSTNAME_COLOR=$GREEN
CLI_HOSTALIAS_COLOR=$RESET
CLI_COLON_COLOR=$RESET
CLI_PWD_COLOR=$YELLOW
CLI_BRANCH_COLOR=$RESET

CLI_ADDED_COLOR=$YELLOW
CLI_UNTRACKED_COLOR=$CYAN
CLI_MODIFIED_COLOR=$BLUE
CLI_DELETED_COLOR=$RED
CLI_RENAMED_COLOR=$MAGENTA
CLI_COPIED_COLOR=$MAGENTA
CLI_UNMERGED_COLOR=$MAGENTA